spring:
  profiles:
    active: dev
---
spring:
  datasource:
    url: ${DATABASE_URL}
    username: ${DATABASE_USERNAME}
    password: ${DATABASE_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
    jpa:
      database-platform: org.hibernate.dialect.MySQL5Dialect
      hibernate:
        ddl-auto: validate
      show-sql: true
    flyway:
      enabled: true
      locations: classpath:db/migration

---
spring:
  profiles: dev
---
spring:
  profiles: prod
---
server:
  port: 8080