spring:
  profiles:
    active: dev
  data:
    rest:
      default-page-size: 100
---
spring:
  datasource:
    url: ${DATABASE_URL}
    username: ${DATABASE_USERNAME}
    password: ${DATABASE_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
    jpa:
    properties.hibernate.dialect: org.hibernate.dialect.MySQL5InnoDBDialect
    properties.hibernate.order_by.default_null_ordering: last
    hibernate:
      ddl-auto: validate
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    flyway:
      ignore-missing-migrations: true
      out-of-order: true
    servlet.multipart:
      max-file-size: 20MB
      max-request-size: 20MB
logging:
  level:
    org:
      springframework:
        data:
          mongodb:
            core:
              MongoTemplate=DEBUG:
stripe:
  secret-key: ${STRIPE_SECRET-KEY}
document:
  category.path: src/main/resources/documents/category
  subcategory.path: src/main/resources/documents/subcategory
  product.path: src/main/resources/documents/product
---
spring:
  data:
    mongodb:
      uri: mongodb://localhost:27017/webshop

---
spring:
  profiles: dev
---
spring:
  profiles: prod
---
server:
  port: 8080